### ISSUE TITLE
Does it support react ^18.2.0

### ISSUE THREAD

**Issue by oleksii-chekhovskyi** [mnbroatch/react-dialogue-tree#23]
Hello mate, I trying to use your project in my pet project and can't figure out  what I do wrong
I use "react": "^18.2.0", "react-dom": "^18.2.0",

page code : 
```
import React from 'react';
import DialogueTree from 'react-dialogue-tree'
import 'react-dialogue-tree/dist/react-dialogue-tree.css'


const Dialog =  () => {

  const dialogue = `
  title: Start
  ---
  Companion: Hi there! What do you feel like doing today?

  -> Player: I want to go swimming.
      Companion: Okay, let's go swimming.
  -> Player: I'd prefer to go hiking.
      Companion: Cool, we'll go hiking then.
  ===  
  `

  return <DialogueTree dialogue={dialogue} />
}

export default Dialog;
```
![image](https://user-images.githubusercontent.com/54133335/206579834-0906be5d-56b9-4e41-8d13-290666e967d2.png)

**Comment by oleksii-chekhovskyi** [comment]
Fixed by moving yous src into my project and running it under my react version.

**Comment by mnbroatch** [comment]
Version 0.9.3 should work correctly with react 18.2.0

**Comment by oleksii-chekhovskyi** [comment]
thx for answer )
